### ISSUE TITLE
Unable to download leaflet from http://leaflet-cdn.s3.amazonaws.com/build/leaflet-0.7.3.zip.

### ISSUE THREAD

**Issue by niccolox** [poetic/rune#80]
am creating new platform in valkyrie vm with poetic makefile and getting leaflet version error

Unable to download leaflet from http://leaflet-cdn.s3.amazonaws.com/build/leaflet-0.7.3.zip.

**Comment by RealLukeMartin** [comment]
Can confirm, having this issue as well.

```
Unable to download leaflet from http://leaflet-cdn.s3.amazonaws.com/build/leaflet-0.7.3.zip.                                                                                               [error]
```

**Comment by RealLukeMartin** [comment]
Hey @niccolox leaflet changed the CDN location, got that fixed here https://github.com/poetic/rune/pull/81
